/**
 * Oxford Phonics World Levels 1-5 Vocabulary for Typing Practice.
 * Structured by phonics rules for young learners (Grade 1-2).
 * Level 1-5: 50 words per level (250 words total).
 */

import type { TypingTarget } from './lessons';

export interface PhonicsWord {
  word: string;
  meaning: string;
  icon: string;
  level: 1 | 2 | 3 | 4 | 5;
  rule: string;
}

export interface PhonicsLevelDef {
  level: 1 | 2 | 3 | 4 | 5;
  id: string;
  titleKey: string;
  title: string;
  subtitle: string;
  icon: string;
  badge: string;
  words: PhonicsWord[];
}

export const PHONICS_WORDS: PhonicsWord[] = [
  // ── Level 1: The Alphabet (字母与字母音 · 50词) ──
  { word: "ant", meaning: "蚂蚁", icon: "🐜", level: 1, rule: "Letter A" },
  { word: "ape", meaning: "猿猴", icon: "🦧", level: 1, rule: "Letter A" },
  { word: "axe", meaning: "斧头", icon: "🪓", level: 1, rule: "Letter A" },
  { word: "apple", meaning: "苹果", icon: "🍎", level: 1, rule: "Letter A" },
  { word: "bed", meaning: "床", icon: "🛏️", level: 1, rule: "Letter B" },
  { word: "bag", meaning: "书包", icon: "🎒", level: 1, rule: "Letter B" },
  { word: "bat", meaning: "球棒", icon: "🏏", level: 1, rule: "Letter B" },
  { word: "bus", meaning: "巴士", icon: "🚌", level: 1, rule: "Letter B" },
  { word: "boy", meaning: "男孩", icon: "👦", level: 1, rule: "Letter B" },
  { word: "cat", meaning: "小猫", icon: "🐱", level: 1, rule: "Letter C" },
  { word: "cup", meaning: "茶杯", icon: "☕", level: 1, rule: "Letter C" },
  { word: "car", meaning: "汽车", icon: "🚗", level: 1, rule: "Letter C" },
  { word: "cow", meaning: "奶牛", icon: "🐄", level: 1, rule: "Letter C" },
  { word: "dog", meaning: "小狗", icon: "🐶", level: 1, rule: "Letter D" },
  { word: "duck", meaning: "鸭子", icon: "🦆", level: 1, rule: "Letter D" },
  { word: "dot", meaning: "圆点", icon: "🟢", level: 1, rule: "Letter D" },
  { word: "dad", meaning: "爸爸", icon: "👨", level: 1, rule: "Letter D" },
  { word: "egg", meaning: "蛋", icon: "🥚", level: 1, rule: "Letter E" },
  { word: "elf", meaning: "精灵", icon: "🧝", level: 1, rule: "Letter E" },
  { word: "eye", meaning: "眼睛", icon: "👁️", level: 1, rule: "Letter E" },
  { word: "fan", meaning: "风扇", icon: "🪭", level: 1, rule: "Letter F" },
  { word: "fox", meaning: "狐狸", icon: "🦊", level: 1, rule: "Letter F" },
  { word: "fish", meaning: "鱼", icon: "🐟", level: 1, rule: "Letter F" },
  { word: "fog", meaning: "大雾", icon: "🌫️", level: 1, rule: "Letter F" },
  { word: "gum", meaning: "口香糖", icon: "🍬", level: 1, rule: "Letter G" },
  { word: "gem", meaning: "宝石", icon: "💎", level: 1, rule: "Letter G" },
  { word: "gas", meaning: "瓦斯", icon: "⛽", level: 1, rule: "Letter G" },
  { word: "hat", meaning: "帽子", icon: "🎩", level: 1, rule: "Letter H" },
  { word: "hen", meaning: "母鸡", icon: "🐔", level: 1, rule: "Letter H" },
  { word: "hot", meaning: "炎热", icon: "♨️", level: 1, rule: "Letter H" },
  { word: "hut", meaning: "小屋", icon: "🛖", level: 1, rule: "Letter H" },
  { word: "ink", meaning: "墨水", icon: "🖋️", level: 1, rule: "Letter I" },
  { word: "ill", meaning: "生病", icon: "🤒", level: 1, rule: "Letter I" },
  { word: "jet", meaning: "喷气机", icon: "✈️", level: 1, rule: "Letter J" },
  { word: "jam", meaning: "果酱", icon: "🍯", level: 1, rule: "Letter J" },
  { word: "jar", meaning: "玻璃罐", icon: "🫙", level: 1, rule: "Letter J" },
  { word: "jog", meaning: "慢跑", icon: "🏃", level: 1, rule: "Letter J" },
  { word: "kid", meaning: "小孩", icon: "🧒", level: 1, rule: "Letter K" },
  { word: "kite", meaning: "风筝", icon: "🪁", level: 1, rule: "Letter K" },
  { word: "key", meaning: "钥匙", icon: "🔑", level: 1, rule: "Letter K" },
  { word: "leg", meaning: "腿", icon: "🦵", level: 1, rule: "Letter L" },
  { word: "lip", meaning: "嘴唇", icon: "👄", level: 1, rule: "Letter L" },
  { word: "log", meaning: "木头", icon: "🪵", level: 1, rule: "Letter L" },
  { word: "lion", meaning: "狮子", icon: "🦁", level: 1, rule: "Letter L" },
  { word: "map", meaning: "地图", icon: "🗺️", level: 1, rule: "Letter M" },
  { word: "mud", meaning: "泥巴", icon: "🪵", level: 1, rule: "Letter M" },
  { word: "mug", meaning: "大杯", icon: "🍺", level: 1, rule: "Letter M" },
  { word: "mop", meaning: "拖把", icon: "🧹", level: 1, rule: "Letter M" },
  { word: "nut", meaning: "坚果", icon: "🥜", level: 1, rule: "Letter N" },
  { word: "net", meaning: "网", icon: "🥅", level: 1, rule: "Letter N" },

  // ── Level 2: Short Vowels (短元音 CVC · 50词) ──
  { word: "bat", meaning: "蝙蝠/球棒", icon: "🦇", level: 2, rule: "Short A" },
  { word: "cat", meaning: "猫咪", icon: "🐱", level: 2, rule: "Short A" },
  { word: "fat", meaning: "肥胖", icon: "🐘", level: 2, rule: "Short A" },
  { word: "hat", meaning: "礼帽", icon: "🎩", level: 2, rule: "Short A" },
  { word: "mat", meaning: "地垫", icon: "🧘", level: 2, rule: "Short A" },
  { word: "rat", meaning: "老鼠", icon: "🐀", level: 2, rule: "Short A" },
  { word: "cap", meaning: "鸭舌帽", icon: "🧢", level: 2, rule: "Short A" },
  { word: "map", meaning: "地图", icon: "🗺️", level: 2, rule: "Short A" },
  { word: "tap", meaning: "水龙头", icon: "🚰", level: 2, rule: "Short A" },
  { word: "dad", meaning: "爸爸", icon: "👨", level: 2, rule: "Short A" },
  { word: "bed", meaning: "木床", icon: "🛏️", level: 2, rule: "Short E" },
  { word: "red", meaning: "红色", icon: "🔴", level: 2, rule: "Short E" },
  { word: "fed", meaning: "喂食", icon: "🍼", level: 2, rule: "Short E" },
  { word: "leg", meaning: "腿部", icon: "🦵", level: 2, rule: "Short E" },
  { word: "peg", meaning: "木桩", icon: "🪝", level: 2, rule: "Short E" },
  { word: "hen", meaning: "母鸡", icon: "🐔", level: 2, rule: "Short E" },
  { word: "pen", meaning: "钢笔", icon: "🖊️", level: 2, rule: "Short E" },
  { word: "ten", meaning: "数字十", icon: "🔟", level: 2, rule: "Short E" },
  { word: "net", meaning: "球网", icon: "🥅", level: 2, rule: "Short E" },
  { word: "pet", meaning: "宠物", icon: "🐕", level: 2, rule: "Short E" },
  { word: "bin", meaning: "垃圾桶", icon: "🗑️", level: 2, rule: "Short I" },
  { word: "pin", meaning: "别针", icon: "📌", level: 2, rule: "Short I" },
  { word: "win", meaning: "获胜", icon: "🏆", level: 2, rule: "Short I" },
  { word: "fin", meaning: "鱼鳍", icon: "🦈", level: 2, rule: "Short I" },
  { word: "dig", meaning: "挖矿", icon: "⛏️", level: 2, rule: "Short I" },
  { word: "pig", meaning: "小猪", icon: "🐷", level: 2, rule: "Short I" },
  { word: "big", meaning: "巨大", icon: "🐘", level: 2, rule: "Short I" },
  { word: "wig", meaning: "假发", icon: "💇", level: 2, rule: "Short I" },
  { word: "hit", meaning: "击中", icon: "🎯", level: 2, rule: "Short I" },
  { word: "sit", meaning: "坐下", icon: "🪑", level: 2, rule: "Short I" },
  { word: "fox", meaning: "狐狸", icon: "🦊", level: 2, rule: "Short O" },
  { word: "box", meaning: "箱子", icon: "📦", level: 2, rule: "Short O" },
  { word: "hot", meaning: "热气", icon: "♨️", level: 2, rule: "Short O" },
  { word: "pot", meaning: "陶罐", icon: "🍲", level: 2, rule: "Short O" },
  { word: "dot", meaning: "圆点", icon: "🟢", level: 2, rule: "Short O" },
  { word: "lot", meaning: "许多", icon: "📦", level: 2, rule: "Short O" },
  { word: "mop", meaning: "拖把", icon: "🧹", level: 2, rule: "Short O" },
  { word: "top", meaning: "陀螺", icon: "🎪", level: 2, rule: "Short O" },
  { word: "fog", meaning: "浓雾", icon: "🌫️", level: 2, rule: "Short O" },
  { word: "log", meaning: "圆木", icon: "🪵", level: 2, rule: "Short O" },
  { word: "bug", meaning: "小虫", icon: "🐛", level: 2, rule: "Short U" },
  { word: "hug", meaning: "拥抱", icon: "🫂", level: 2, rule: "Short U" },
  { word: "jug", meaning: "水壶", icon: "🏺", level: 2, rule: "Short U" },
  { word: "mug", meaning: "马克杯", icon: "🍺", level: 2, rule: "Short U" },
  { word: "rug", meaning: "小地毯", icon: "🧶", level: 2, rule: "Short U" },
  { word: "cup", meaning: "水杯", icon: "☕", level: 2, rule: "Short U" },
  { word: "pup", meaning: "小狗", icon: "🐶", level: 2, rule: "Short U" },
  { word: "gum", meaning: "树胶", icon: "🍬", level: 2, rule: "Short U" },
  { word: "hut", meaning: "茅屋", icon: "🛖", level: 2, rule: "Short U" },
  { word: "nut", meaning: "坚果", icon: "🥜", level: 2, rule: "Short U" },

  // ── Level 3: Long Vowels (长元音 Magic e · 50词) ──
  { word: "bake", meaning: "烘焙", icon: "🍞", level: 3, rule: "a_e" },
  { word: "cake", meaning: "蛋糕", icon: "🎂", level: 3, rule: "a_e" },
  { word: "lake", meaning: "湖泊", icon: "🏞️", level: 3, rule: "a_e" },
  { word: "make", meaning: "制作", icon: "🛠️", level: 3, rule: "a_e" },
  { word: "take", meaning: "拿取", icon: "🤲", level: 3, rule: "a_e" },
  { word: "game", meaning: "游戏", icon: "🎮", level: 3, rule: "a_e" },
  { word: "name", meaning: "名字", icon: "🏷️", level: 3, rule: "a_e" },
  { word: "same", meaning: "相同", icon: "🟰", level: 3, rule: "a_e" },
  { word: "gate", meaning: "大门", icon: "⛩️", level: 3, rule: "a_e" },
  { word: "late", meaning: "迟到", icon: "⏰", level: 3, rule: "a_e" },
  { word: "cape", meaning: "披风", icon: "🦸", level: 3, rule: "a_e" },
  { word: "tape", meaning: "胶带", icon: "📼", level: 3, rule: "a_e" },
  { word: "cave", meaning: "洞穴", icon: "🕳️", level: 3, rule: "a_e" },
  { word: "wave", meaning: "海浪", icon: "🌊", level: 3, rule: "a_e" },
  { word: "bike", meaning: "自行车", icon: "🚲", level: 3, rule: "i_e" },
  { word: "hike", meaning: "徒步", icon: "🥾", level: 3, rule: "i_e" },
  { word: "like", meaning: "喜欢", icon: "👍", level: 3, rule: "i_e" },
  { word: "kite", meaning: "风筝", icon: "🪁", level: 3, rule: "i_e" },
  { word: "bite", meaning: "咬一口", icon: "🦷", level: 3, rule: "i_e" },
  { word: "line", meaning: "直线", icon: "📏", level: 3, rule: "i_e" },
  { word: "fine", meaning: "晴好", icon: "👌", level: 3, rule: "i_e" },
  { word: "mine", meaning: "挖矿/我的", icon: "⛏️", level: 3, rule: "i_e" },
  { word: "nine", meaning: "数字九", icon: "9️⃣", level: 3, rule: "i_e" },
  { word: "pipe", meaning: "管道", icon: "🪈", level: 3, rule: "i_e" },
  { word: "ripe", meaning: "成熟", icon: "🍎", level: 3, rule: "i_e" },
  { word: "fire", meaning: "火焰", icon: "🔥", level: 3, rule: "i_e" },
  { word: "rice", meaning: "米饭", icon: "🍚", level: 3, rule: "i_e" },
  { word: "time", meaning: "时间", icon: "⏰", level: 3, rule: "i_e" },
  { word: "bone", meaning: "骨头", icon: "🦴", level: 3, rule: "o_e" },
  { word: "cone", meaning: "甜筒", icon: "🍦", level: 3, rule: "o_e" },
  { word: "zone", meaning: "区域", icon: "🌐", level: 3, rule: "o_e" },
  { word: "home", meaning: "家园", icon: "🏠", level: 3, rule: "o_e" },
  { word: "dome", meaning: "穹顶", icon: "🏟️", level: 3, rule: "o_e" },
  { word: "hole", meaning: "地洞", icon: "🕳️", level: 3, rule: "o_e" },
  { word: "mole", meaning: "鼹鼠", icon: "🐾", level: 3, rule: "o_e" },
  { word: "pole", meaning: "立柱", icon: "💈", level: 3, rule: "o_e" },
  { word: "hope", meaning: "希望", icon: "🌟", level: 3, rule: "o_e" },
  { word: "rope", meaning: "绳子", icon: "🪢", level: 3, rule: "o_e" },
  { word: "rose", meaning: "玫瑰", icon: "🌹", level: 3, rule: "o_e" },
  { word: "nose", meaning: "鼻子", icon: "👃", level: 3, rule: "o_e" },
  { word: "note", meaning: "便签", icon: "📝", level: 3, rule: "o_e" },
  { word: "vote", meaning: "投票", icon: "🗳️", level: 3, rule: "o_e" },
  { word: "cute", meaning: "可爱", icon: "😺", level: 3, rule: "u_e" },
  { word: "cube", meaning: "方块", icon: "🧊", level: 3, rule: "u_e" },
  { word: "flute", meaning: "长笛", icon: "🪈", level: 3, rule: "u_e" },
  { word: "mule", meaning: "骡子", icon: "🫏", level: 3, rule: "u_e" },
  { word: "tube", meaning: "试管", icon: "🧪", level: 3, rule: "u_e" },
  { word: "tune", meaning: "曲调", icon: "🎶", level: 3, rule: "u_e" },
  { word: "huge", meaning: "巨大", icon: "🦖", level: 3, rule: "u_e" },
  { word: "rule", meaning: "规则", icon: "📜", level: 3, rule: "u_e" },

  // ── Level 4: Consonant Blends (辅音字母组合 · 50词) ──
  { word: "ship", meaning: "轮船", icon: "🚢", level: 4, rule: "sh" },
  { word: "shop", meaning: "商店", icon: "🏪", level: 4, rule: "sh" },
  { word: "shut", meaning: "关门", icon: "🚪", level: 4, rule: "sh" },
  { word: "fish", meaning: "游鱼", icon: "🐟", level: 4, rule: "sh" },
  { word: "dish", meaning: "盘子", icon: "🍽️", level: 4, rule: "sh" },
  { word: "chick", meaning: "小鸡", icon: "🐥", level: 4, rule: "ch" },
  { word: "chin", meaning: "下巴", icon: "🧔", level: 4, rule: "ch" },
  { word: "chop", meaning: "砍伐", icon: "🪓", level: 4, rule: "ch" },
  { word: "rich", meaning: "富有", icon: "💰", level: 4, rule: "ch" },
  { word: "much", meaning: "许多", icon: "➕", level: 4, rule: "ch" },
  { word: "thin", meaning: "细薄", icon: "🪶", level: 4, rule: "th" },
  { word: "thick", meaning: "厚实", icon: "🧱", level: 4, rule: "th" },
  { word: "math", meaning: "数学", icon: "🧮", level: 4, rule: "th" },
  { word: "path", meaning: "小径", icon: "🛤️", level: 4, rule: "th" },
  { word: "whale", meaning: "鲸鱼", icon: "🐋", level: 4, rule: "wh" },
  { word: "white", meaning: "白色", icon: "⚪", level: 4, rule: "wh" },
  { word: "wheel", meaning: "车轮", icon: "🎡", level: 4, rule: "wh" },
  { word: "whip", meaning: "皮鞭", icon: "➰", level: 4, rule: "wh" },
  { word: "black", meaning: "黑色", icon: "⚫", level: 4, rule: "bl" },
  { word: "blow", meaning: "吹气", icon: "🌬️", level: 4, rule: "bl" },
  { word: "blue", meaning: "蓝色", icon: "🔵", level: 4, rule: "bl" },
  { word: "clock", meaning: "时钟", icon: "⏰", level: 4, rule: "cl" },
  { word: "clap", meaning: "拍手", icon: "👏", level: 4, rule: "cl" },
  { word: "flag", meaning: "旗帜", icon: "🚩", level: 4, rule: "fl" },
  { word: "flat", meaning: "平整", icon: "🥏", level: 4, rule: "fl" },
  { word: "fly", meaning: "飞行", icon: "🪰", level: 4, rule: "fl" },
  { word: "glass", meaning: "玻璃杯", icon: "🥛", level: 4, rule: "gl" },
  { word: "glad", meaning: "高兴", icon: "😃", level: 4, rule: "gl" },
  { word: "slide", meaning: "滑梯", icon: "🛝", level: 4, rule: "sl" },
  { word: "slow", meaning: "缓慢", icon: "🐢", level: 4, rule: "sl" },
  { word: "slip", meaning: "滑倒", icon: "🍌", level: 4, rule: "sl" },
  { word: "crab", meaning: "螃蟹", icon: "🦀", level: 4, rule: "cr" },
  { word: "crop", meaning: "庄稼", icon: "🌾", level: 4, rule: "cr" },
  { word: "frog", meaning: "青蛙", icon: "🐸", level: 4, rule: "fr" },
  { word: "from", meaning: "来自", icon: "➡️", level: 4, rule: "fr" },
  { word: "free", meaning: "自由", icon: "🕊️", level: 4, rule: "fr" },
  { word: "drum", meaning: "击鼓", icon: "🥁", level: 4, rule: "dr" },
  { word: "drop", meaning: "水滴", icon: "💧", level: 4, rule: "dr" },
  { word: "draw", meaning: "画画", icon: "🎨", level: 4, rule: "dr" },
  { word: "grape", meaning: "葡萄", icon: "🍇", level: 4, rule: "gr" },
  { word: "grass", meaning: "青草", icon: "🌱", level: 4, rule: "gr" },
  { word: "green", meaning: "绿色", icon: "🟢", level: 4, rule: "gr" },
  { word: "tree", meaning: "大树", icon: "🌳", level: 4, rule: "tr" },
  { word: "trip", meaning: "旅行", icon: "🧳", level: 4, rule: "tr" },
  { word: "train", meaning: "列车", icon: "🚂", level: 4, rule: "tr" },
  { word: "star", meaning: "星星", icon: "⭐", level: 4, rule: "st" },
  { word: "stop", meaning: "停步", icon: "🛑", level: 4, rule: "st" },
  { word: "step", meaning: "台阶", icon: "🪜", level: 4, rule: "st" },
  { word: "spoon", meaning: "汤匙", icon: "🥄", level: 4, rule: "sp" },
  { word: "swim", meaning: "游泳", icon: "🏊", level: 4, rule: "sw" },

  // ── Level 5: Letter Combinations (进阶双元音 · 50词) ──
  { word: "bee", meaning: "蜜蜂", icon: "🐝", level: 5, rule: "ee" },
  { word: "see", meaning: "看见", icon: "👀", level: 5, rule: "ee" },
  { word: "tree", meaning: "树林", icon: "🌲", level: 5, rule: "ee" },
  { word: "feel", meaning: "感觉", icon: "❤️", level: 5, rule: "ee" },
  { word: "meet", meaning: "相遇", icon: "🤝", level: 5, rule: "ee" },
  { word: "sleep", meaning: "睡眠", icon: "😴", level: 5, rule: "ee" },
  { word: "sea", meaning: "大海", icon: "🌊", level: 5, rule: "ea" },
  { word: "tea", meaning: "茶水", icon: "🍵", level: 5, rule: "ea" },
  { word: "pea", meaning: "豌豆", icon: "🫛", level: 5, rule: "ea" },
  { word: "leaf", meaning: "树叶", icon: "🍃", level: 5, rule: "ea" },
  { word: "meat", meaning: "肉类", icon: "🥩", level: 5, rule: "ea" },
  { word: "read", meaning: "读书", icon: "📖", level: 5, rule: "ea" },
  { word: "team", meaning: "战队", icon: "👥", level: 5, rule: "ea" },
  { word: "rain", meaning: "下雨", icon: "🌧️", level: 5, rule: "ai" },
  { word: "tail", meaning: "尾巴", icon: "🐕", level: 5, rule: "ai" },
  { word: "sail", meaning: "扬帆", icon: "⛵", level: 5, rule: "ai" },
  { word: "wait", meaning: "等待", icon: "⏳", level: 5, rule: "ai" },
  { word: "nail", meaning: "钉子", icon: "🔩", level: 5, rule: "ai" },
  { word: "day", meaning: "白天", icon: "☀️", level: 5, rule: "ay" },
  { word: "play", meaning: "游玩", icon: "🎮", level: 5, rule: "ay" },
  { word: "say", meaning: "说话", icon: "🗣️", level: 5, rule: "ay" },
  { word: "way", meaning: "道路", icon: "🛣️", level: 5, rule: "ay" },
  { word: "stay", meaning: "停留", icon: "🏠", level: 5, rule: "ay" },
  { word: "boat", meaning: "木舟", icon: "⛵", level: 5, rule: "oa" },
  { word: "coat", meaning: "外套", icon: "🧥", level: 5, rule: "oa" },
  { word: "road", meaning: "公路", icon: "🛣️", level: 5, rule: "oa" },
  { word: "goat", meaning: "山羊", icon: "🐐", level: 5, rule: "oa" },
  { word: "soap", meaning: "肥皂", icon: "🧼", level: 5, rule: "oa" },
  { word: "snow", meaning: "白雪", icon: "❄️", level: 5, rule: "ow" },
  { word: "blow", meaning: "吹风", icon: "🌬️", level: 5, rule: "ow" },
  { word: "slow", meaning: "减速", icon: "🐢", level: 5, rule: "ow" },
  { word: "glow", meaning: "发光", icon: "✨", level: 5, rule: "ow" },
  { word: "row", meaning: "划船", icon: "🚣", level: 5, rule: "ow" },
  { word: "book", meaning: "书籍", icon: "📚", level: 5, rule: "oo" },
  { word: "cook", meaning: "下厨", icon: "🍳", level: 5, rule: "oo" },
  { word: "look", meaning: "注视", icon: "🔎", level: 5, rule: "oo" },
  { word: "moon", meaning: "月亮", icon: "🌕", level: 5, rule: "oo" },
  { word: "zoo", meaning: "动物园", icon: "🦁", level: 5, rule: "oo" },
  { word: "cool", meaning: "凉爽", icon: "😎", level: 5, rule: "oo" },
  { word: "coin", meaning: "金币", icon: "🪙", level: 5, rule: "oi" },
  { word: "join", meaning: "加入", icon: "🤝", level: 5, rule: "oi" },
  { word: "boy", meaning: "少年", icon: "👦", level: 5, rule: "oy" },
  { word: "toy", meaning: "玩具", icon: "🧸", level: 5, rule: "oy" },
  { word: "cloud", meaning: "云朵", icon: "☁️", level: 5, rule: "ou" },
  { word: "house", meaning: "房屋", icon: "🏠", level: 5, rule: "ou" },
  { word: "mouse", meaning: "耗子", icon: "🐭", level: 5, rule: "ou" },
  { word: "out", meaning: "向外", icon: "🚪", level: 5, rule: "ou" },
  { word: "cow", meaning: "黄牛", icon: "🐄", level: 5, rule: "ow" },
  { word: "owl", meaning: "猫头鹰", icon: "🦉", level: 5, rule: "ow" },
  { word: "town", meaning: "城镇", icon: "🏘️", level: 5, rule: "ow" },
];

export const PHONICS_LEVELS: PhonicsLevelDef[] = [
  {
    level: 1,
    id: 'phonics-l1',
    titleKey: 'Typing.phonics.l1',
    title: 'Level 1: 字母启蒙音',
    subtitle: 'The Alphabet · 26个英文字母的发音感知 (apple, bed, cat...)',
    icon: '🍎',
    badge: '字母与发音',
    words: PHONICS_WORDS.filter((w) => w.level === 1),
  },
  {
    level: 2,
    id: 'phonics-l2',
    titleKey: 'Typing.phonics.l2',
    title: 'Level 2: 短元音拼读',
    subtitle: 'Short Vowels · a / e / i / o / u 基础三字拼读 CVC (bat, red, pig...)',
    icon: '🐱',
    badge: 'CVC 短元音',
    words: PHONICS_WORDS.filter((w) => w.level === 2),
  },
  {
    level: 3,
    id: 'phonics-l3',
    titleKey: 'Typing.phonics.l3',
    title: 'Level 3: 长元音 Magic e',
    subtitle: 'Long Vowels · 魔法字母 e 的长元音规则 (lake, bike, home...)',
    icon: '✨',
    badge: 'Magic e 长音',
    words: PHONICS_WORDS.filter((w) => w.level === 3),
  },
  {
    level: 4,
    id: 'phonics-l4',
    titleKey: 'Typing.phonics.l4',
    title: 'Level 4: 辅音组合',
    subtitle: 'Consonant Blends · 常见辅音字母组合 (ship, tree, frog...)',
    icon: '🐸',
    badge: '辅音组合拼读',
    words: PHONICS_WORDS.filter((w) => w.level === 4),
  },
  {
    level: 5,
    id: 'phonics-l5',
    titleKey: 'Typing.phonics.l5',
    title: 'Level 5: 元音组合',
    subtitle: 'Letter Combinations · 进阶双元音与变音 (rain, boat, moon...)',
    icon: '🌈',
    badge: '进阶双元音',
    words: PHONICS_WORDS.filter((w) => w.level === 5),
  },
];

export function getPhonicsLevel(level: number): PhonicsLevelDef {
  return PHONICS_LEVELS.find((l) => l.level === level) ?? PHONICS_LEVELS[0];
}

export function pickPhonicsTarget(level: number, exclude: Set<string> = new Set()): TypingTarget {
  const lvl = getPhonicsLevel(level);
  let pool = lvl.words.filter((w) => !exclude.has(w.word[0]));
  if (pool.length === 0) pool = lvl.words;
  const picked = pool[Math.floor(Math.random() * pool.length)];

  return {
    display: picked.word.toUpperCase(),
    answer: picked.word.toLowerCase(),
    hint: `${picked.icon} ${picked.meaning}`,
  };
}

export function makePhonicsBossTarget(level: number): TypingTarget {
  const lvl = getPhonicsLevel(level);
  // Pick a longer word or 2 short words combined
  const candidates = [...lvl.words].sort((a, b) => b.word.length - a.word.length);
  const picked = candidates[Math.floor(Math.random() * Math.min(5, candidates.length))];

  return {
    display: `${picked.icon} ${picked.word.toUpperCase()}`,
    answer: picked.word.toLowerCase(),
    hint: `⭐ BOSS 单词: ${picked.meaning}`,
  };
}
